# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/services/product-service/ProductService.API/ProductService.API.csproj", "src/services/product-service/ProductService.API/"]
COPY ["src/services/product-service/ProductService.Applilcation/ProductService.Applilcation.csproj", "src/services/product-service/ProductService.Applilcation/"]
COPY ["src/services/product-service/ProductService.Domain/ProductService.Domain.csproj", "src/services/product-service/ProductService.Domain/"]
COPY ["src/building-blocks/Domain.SeedWork/Domain.SeedWork.csproj", "src/building-blocks/Domain.SeedWork/"]
COPY ["src/services/product-service/ProductService.Infrastructure/ProductService.Infrastructure.csproj", "src/services/product-service/ProductService.Infrastructure/"]
COPY ["src/services/product-service/ProductService.Infrastructure.IoC/ProductService.Infrastructure.IoC.csproj", "src/services/product-service/ProductService.Infrastructure.IoC/"]
RUN dotnet restore "./src/services/product-service/ProductService.API/ProductService.API.csproj"
COPY . .
WORKDIR "/src/src/services/product-service/ProductService.API"
RUN dotnet build "./ProductService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ProductService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProductService.API.dll"]