services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customerserviceapi
    build:
      context: .
      dockerfile: src/services/customer-service/CustomerService.API/Dockerfile

  customer.db:
    image: mcr.microsoft.com/mssql/server

  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: src/services/product-service/ProductService.API/Dockerfile

  product.db:
    image: mysql:latest

  order.db:
    image: mongo:latest


  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: src/services/order-service/OrderService.API/Dockerfile

