services:
  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DB_HOST=customer.db
      - DB_NAME=CustomerDB
      - DB_PASSWORD=p@sswordD1
      - JWT_SECRET=xiyvfbhzNL8Br7Rl5jfhposePmkLkTg3
    ports:
      - "8080"
      - "8081"
    depends_on:
      - customer.db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  customer.db:
    container_name: customer.db
    environment:
      - SA_PASSWORD=p@sswordD1
      - ACCEPT_EULA=Y
    volumes:
      - customerdbdata:/var/opt/mssql
    ports:
      - "1401:1433"
    restart: always

  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_Host=productdb
      - DB_Name=dms_product
      - DB_Password=123456
      - DB_Port=3306
      - JWT_SECRET=xiyvfbhzNL8Br7Rl5jfhposePmkLkTg3
    ports:
      - "8080"
    depends_on:
      - product.db

  product.db:
    container_name: product.db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  order.db:
    container_name: order.db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  orderservice.api:
    container_name: orderservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT_SECRET=xiyvfbhzNL8Br7Rl5jfhposePmkLkTg3
    ports:
      - "8080"
    depends_on:
      - order.db

  identityservice.api:
    container_name: identityservice.api
    depends_on:
      - identity.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT_SECRET=xiyvfbhzNL8Br7Rl5jfhposePmkLkTg3
      - JWT_Expiration=20
      - JWT_Issuer=DMS.Identity
      - JWT_Audience=DMS.Identity.Client
      - DB_Host=identitydb
      - DB_Name=dms_identity
      - DB_UserName=admin
      - DB_Password=admin
      - DB_Port=5432
    ports:
      - "8080"
  
  identity.db:
    container_name: identity.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  customerdbdata:  
  mysql_data:
  mongo_data:
  postgres_data:
    
  



