<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.1.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.0.0" />		
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.0.1" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderService.Application\OrderService.Application.csproj" />
    <ProjectReference Include="..\OrderService.Infrastructure.IoC\OrderService.Infrastructure.IoC.csproj" />
  </ItemGroup>

</Project>
